[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bun_kit = "2A3hSE4yGd6t7W4CytLYz8gmKpCcLZuEvCJy2rzYijMr"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo nextest run"

[hooks]
