[tools]
bun = "latest"
sccache = "0.14.0"
"npm:codama" = "1.5.1"
"npm:oxfmt" = "0.41.0"
"npm:oxlint" = "1.56.0"
"npm:oxlint-tsgolint" = "0.17.1"

[tasks.setup]
description = "Install the Dependencies"
run = "bun install"

[tasks.sync]
description = "Sync Anchor keys"
run = "anchor keys sync"

[tasks.build]
depends = ["sync"]
description = "Build the Anchor Program"
# run = "anchor build && codama run rust"
run = "anchor build"

[tasks.deploy]
depends = ["build"]
description = "Deploy Anchor program to surfpool"
run = "anchor program deploy"

[tasks.lint]
description = "Lint the project"
run = "oxlint --type-aware --type-check --fix"

[tasks.fmt]
description = "format the project"
run = "oxfmt && cargo fmt --all"

[tasks.test]
depends = ["build", "lint", "fmt"]
description = "Test the Anchor Program"
run = "anchor test"

[tasks.update]
description = "Update the Bun packages and Cargo dependencies"
run = "bun update && cargo update"

[tasks.clean]
description = "Clean the Cache"
run = "rm -rf target node_modules clients .surfpool runbooks txtx.yml"

[shell_alias]
m = "mise"

[settings]
jobs = 1

[settings.npm]
package_manager = "bun"
